version: '3.5'

services:
  db:
    build: ./db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: app.env
    networks:
      - porter

  app:
    build:
      context: ./app
    restart: always
    env_file: app.env
    environment:
      APP_ROOT: /app
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      FLASK_SETTINGS: /app/config.py
    depends_on:
      - db
    networks:
      - porter

volumes:
  pgdata:

networks:
  porter:
